# Generated by Django 5.0 on 2023-12-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('animal_image', models.ImageField(upload_to='animals')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='input_time',
            field=models.DateTimeField(),
        ),
    ]
